version: '3.8'

networks:
  mongo-network:
    driver: bridge
    
services:
  mongodb1:
    hostname: mongodb1
    container_name: mongodb1
    image: mongo
    networks:
      - mongo-network
    volumes:
      - ./data/db-01:/data/db
    ports:
      - 27017:27017
    depends_on:
      - mongodb2
      - mongodb3
      - mongodb4
      - mongodb5
    command: mongod --bind_ip_all --replSet rs0
    restart: unless-stopped

  mongodb2:
    hostname: mongodb2
    container_name: mongodb2
    image: mongo
    networks:
      - mongo-network
    volumes:
      - ./data/db-02:/data/db
    ports:
      - 27018:27017
    depends_on:
      - mongodb3
      - mongodb4
      - mongodb5
    command: mongod --bind_ip_all --replSet rs0
    restart: unless-stopped


  mongodb3:
    hostname: mongodb3
    container_name: mongodb3
    image: mongo
    networks:
      - mongo-network
    volumes:
      - ./data/db-03:/data/db
    ports:
      - 27019:27017
    depends_on:
      - mongodb4
      - mongodb5
    command: mongod --bind_ip_all --replSet rs0
    restart: unless-stopped


  mongodb4:
    hostname: mongodb4
    container_name: mongodb4
    image: mongo
    networks:
      - mongo-network
    volumes:
      - ./data/db-04:/data/db
    ports:
      - 27020:27017
    depends_on: 
      - mongodb5
    command: mongod --bind_ip_all --replSet rs0
    restart: unless-stopped

  
  mongodb5:
    hostname: mongodb5
    container_name: mongodb5
    image: mongo
    networks:
      - mongo-network
    volumes:
      - ./data/db-05:/data/db
    ports:
      - 27021:27017
    command: mongod --bind_ip_all --replSet rs0
    restart: unless-stopped

  repl-helper:
    container_name: repl-helper
    image: repl-helper
    networks:
      - mongo-network
    depends_on: 
      - mongodb1
    # volumes: 
    #   - ./innerSetup.sh:/configs/innerSetup.sh
    #   - ./replicaInit.js:/configs/replicaInit.js
    # command: sh /configs/innerSetup.sh