version: '3.8'

networks:
  backend:
    driver: bridge

services: 
  mongodb1:
    container_name: mongodb1
    image: mongo
    networks:
      - backend
    volumes:
      - ./data/db-01:/data/db
    ports:
      - 27017:27017
    command: mongod --bind_ip_all --replSet rs0
    restart: unless-stopped

  mongodb2:
    container_name: mongodb2
    image: mongo
    networks:
      - backend
    volumes:
      - ./data/db-02:/data/db
    ports:
      - 27018:27017
    depends_on:
      - mongodb1
    command: mongod --bind_ip_all --replSet rs0
    restart: unless-stopped

  mongodb3:
    container_name: mongodb3
    image: mongo
    networks:
      - backend
    volumes:
      - ./data/db-03:/data/db
    ports:
      - 27019:27017
    depends_on:
      - mongodb2
    command: mongod --bind_ip_all --replSet rs0
    restart: unless-stopped

  mongodb4:
    container_name: mongodb4
    image: mongo
    networks:
      - backend
    volumes:
      - ./data/db-04:/data/db
    ports:
      - 27020:27017
    depends_on: 
      - mongodb3
    command: mongod --bind_ip_all --replSet rs0
    restart: unless-stopped

  mongodb5:
    container_name: mongodb5
    image: mongo
    networks:
      - backend
    volumes:
      - ./data/db-05:/data/db
    ports:
      - 27021:27017
    depends_on:
      - mongodb4
    command: mongod --bind_ip_all --replSet rs0
    restart: unless-stopped

  repl-helper:
    container_name: repl-helper
    image: repl-helper
    networks:
      - backend
    depends_on: 
      - mongodb5
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 3000:3000
    expose:
      - "3000"
    volumes: 
      - ./server:/app
    networks: 
      - backend