version: '3'

networks:
  mongo-network:
    driver: bridge
    
services:
  mongodb1:
    hostname: mongodb1
    container_name: mongodb1
    image: mongo
    expose: 
      - 27017
    networks:
      - mongo-network
    volumes:
      - ./data/db-01:/data/db
      - ./scripts:/scripts
    ports:
      - 27017:27017
    depends_on:
      - mongodb2
      - mongodb3
    entrypoint: [ "mongod", "--bind_ip_all", "--replSet", "mongo-repl" ]
    restart: always

  mongodb2:
    hostname: mongodb2
    container_name: mongodb2
    image: mongo
    expose: 
      - 27017
    networks:
      - mongo-network
    volumes:
      - ./data/db-02:/data/db
      - ./scripts:/scripts
    ports:
      - 27018:27017
    depends_on:
      - mongodb3
    entrypoint: [ "mongod", "--bind_ip_all", "--replSet", "mongo-repl" ]
    restart: always

  mongodb3:
    hostname: mongodb3
    container_name: mongodb3
    image: mongo
    expose: 
      - 27017
    networks:
      - mongo-network
    volumes:
      - ./data/db-03:/data/db
      - ./scripts:/scripts
    ports:
      - 27019:27017
    entrypoint: [ "mongod", "--bind_ip_all", "--replSet", "mongo-repl" ]
    restart: always

  mongo-repl-helper:
    hostname: mongo-repl-helper
    container_name: mongo-repl-helper
    image: mongo
    networks:
      - mongo-network
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    volumes:
      - ./scripts/init.sh:/scripts/init.sh
    entrypoint: ["sh","/scripts/init.sh"]
